// Code generated by Boiler; YOU MUST CHANGE THIS.

package dummy_service

import (
	"github.com/ushakovn/boiler/pkg/app"
	docs "main/docs"
	desc "main/internal/pb/loghouse_test"
)

type DummyService struct {
	desc.UnimplementedDummyServiceServer
}

func NewDummyService() *DummyService {
	return &DummyService{}
}

// RegisterService Code generated by Boiler; DO NOT EDIT.
func (s *DummyService) RegisterService(params *app.RegisterParams) error {
	params.SetServiceType(app.GrpcServiceTyp)
	grpcParams := params.Grpc()
	grpcParams.SetOpenAPIDoc(docs.Swagger)
	desc.RegisterDummyServiceServer(grpcParams.GrpcServiceRegistrar(), s)

	return desc.RegisterDummyServiceHandlerFromEndpoint(
		params.Context(),
		grpcParams.GrpcHttpProxyServeMux(),
		grpcParams.GrpcServerEndpoint(),
		grpcParams.GrpcClientOptions(),
	)
}
