// Code generated by Boiler. YOU MAY CHANGE THIS
package main

import (
	"github.com/ushakovn/boiler/pkg/app"
	"github.com/ushakovn/ushakovn-org/loghouse-test/internal/app/dummy_service"
)

func main() {
	a := app.NewApp()
	s := dummy_service.NewDummyService()
	a.Run(s)
}
