// Code generated by Boiler; YOU MUST CHANGE THIS.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.0
// source: api/loghouse_test/loghouse_test.proto

package loghouse_test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dummy_Enum int32

const (
	Dummy_UNKNOWN    Dummy_Enum = 0
	Dummy_SOME_VALUE Dummy_Enum = 1
)

// Enum value maps for Dummy_Enum.
var (
	Dummy_Enum_name = map[int32]string{
		0: "UNKNOWN",
		1: "SOME_VALUE",
	}
	Dummy_Enum_value = map[string]int32{
		"UNKNOWN":    0,
		"SOME_VALUE": 1,
	}
)

func (x Dummy_Enum) Enum() *Dummy_Enum {
	p := new(Dummy_Enum)
	*p = x
	return p
}

func (x Dummy_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Dummy_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_loghouse_test_loghouse_test_proto_enumTypes[0].Descriptor()
}

func (Dummy_Enum) Type() protoreflect.EnumType {
	return &file_api_loghouse_test_loghouse_test_proto_enumTypes[0]
}

func (x Dummy_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Dummy_Enum.Descriptor instead.
func (Dummy_Enum) EnumDescriptor() ([]byte, []int) {
	return file_api_loghouse_test_loghouse_test_proto_rawDescGZIP(), []int{2, 0}
}

type GetDummyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SomeField int32  `protobuf:"varint,2,opt,name=some_field,json=someField,proto3" json:"some_field,omitempty"`
}

func (x *GetDummyRequest) Reset() {
	*x = GetDummyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loghouse_test_loghouse_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDummyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummyRequest) ProtoMessage() {}

func (x *GetDummyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_loghouse_test_loghouse_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummyRequest.ProtoReflect.Descriptor instead.
func (*GetDummyRequest) Descriptor() ([]byte, []int) {
	return file_api_loghouse_test_loghouse_test_proto_rawDescGZIP(), []int{0}
}

func (x *GetDummyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDummyRequest) GetSomeField() int32 {
	if x != nil {
		return x.SomeField
	}
	return 0
}

type GetDummyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy []*Dummy `protobuf:"bytes,1,rep,name=dummy,proto3" json:"dummy,omitempty"`
}

func (x *GetDummyResponse) Reset() {
	*x = GetDummyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loghouse_test_loghouse_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDummyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDummyResponse) ProtoMessage() {}

func (x *GetDummyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_loghouse_test_loghouse_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDummyResponse.ProtoReflect.Descriptor instead.
func (*GetDummyResponse) Descriptor() ([]byte, []int) {
	return file_api_loghouse_test_loghouse_test_proto_rawDescGZIP(), []int{1}
}

func (x *GetDummyResponse) GetDummy() []*Dummy {
	if x != nil {
		return x.Dummy
	}
	return nil
}

type Dummy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Field string     `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Enum  Dummy_Enum `protobuf:"varint,3,opt,name=enum,proto3,enum=loghouse_test.Dummy_Enum" json:"enum,omitempty"`
}

func (x *Dummy) Reset() {
	*x = Dummy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_loghouse_test_loghouse_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dummy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dummy) ProtoMessage() {}

func (x *Dummy) ProtoReflect() protoreflect.Message {
	mi := &file_api_loghouse_test_loghouse_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dummy.ProtoReflect.Descriptor instead.
func (*Dummy) Descriptor() ([]byte, []int) {
	return file_api_loghouse_test_loghouse_test_proto_rawDescGZIP(), []int{2}
}

func (x *Dummy) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Dummy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Dummy) GetEnum() Dummy_Enum {
	if x != nil {
		return x.Enum
	}
	return Dummy_UNKNOWN
}

var File_api_loghouse_test_loghouse_test_proto protoreflect.FileDescriptor

var file_api_loghouse_test_loghouse_test_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x2f, 0x6c, 0x6f, 0x67, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6c, 0x6f, 0x67, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x22, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d,
	0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d,
	0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73,
	0x6f, 0x6d, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x44,
	0x75, 0x6d, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05,
	0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x6f,
	0x67, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x52, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x22, 0x81, 0x01, 0x0a, 0x05, 0x44, 0x75, 0x6d,
	0x6d, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x23, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x4f, 0x4d, 0x45, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x01, 0x32, 0x5b, 0x0a, 0x0c,
	0x44, 0x75, 0x6d, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x12, 0x1e, 0x2e, 0x6c, 0x6f, 0x67, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x6f, 0x67, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x58, 0x5a, 0x56, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x73, 0x68, 0x61, 0x6b, 0x6f, 0x76, 0x6e,
	0x2f, 0x75, 0x73, 0x68, 0x61, 0x6b, 0x6f, 0x76, 0x6e, 0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x6c, 0x6f,
	0x67, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x67, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x5f, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x6c, 0x6f, 0x67, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_loghouse_test_loghouse_test_proto_rawDescOnce sync.Once
	file_api_loghouse_test_loghouse_test_proto_rawDescData = file_api_loghouse_test_loghouse_test_proto_rawDesc
)

func file_api_loghouse_test_loghouse_test_proto_rawDescGZIP() []byte {
	file_api_loghouse_test_loghouse_test_proto_rawDescOnce.Do(func() {
		file_api_loghouse_test_loghouse_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_loghouse_test_loghouse_test_proto_rawDescData)
	})
	return file_api_loghouse_test_loghouse_test_proto_rawDescData
}

var file_api_loghouse_test_loghouse_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_loghouse_test_loghouse_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_loghouse_test_loghouse_test_proto_goTypes = []interface{}{
	(Dummy_Enum)(0),          // 0: loghouse_test.Dummy.Enum
	(*GetDummyRequest)(nil),  // 1: loghouse_test.GetDummyRequest
	(*GetDummyResponse)(nil), // 2: loghouse_test.GetDummyResponse
	(*Dummy)(nil),            // 3: loghouse_test.Dummy
}
var file_api_loghouse_test_loghouse_test_proto_depIdxs = []int32{
	3, // 0: loghouse_test.GetDummyResponse.dummy:type_name -> loghouse_test.Dummy
	0, // 1: loghouse_test.Dummy.enum:type_name -> loghouse_test.Dummy.Enum
	1, // 2: loghouse_test.DummyService.GetDummy:input_type -> loghouse_test.GetDummyRequest
	2, // 3: loghouse_test.DummyService.GetDummy:output_type -> loghouse_test.GetDummyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_loghouse_test_loghouse_test_proto_init() }
func file_api_loghouse_test_loghouse_test_proto_init() {
	if File_api_loghouse_test_loghouse_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_loghouse_test_loghouse_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDummyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_loghouse_test_loghouse_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDummyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_loghouse_test_loghouse_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dummy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_loghouse_test_loghouse_test_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_loghouse_test_loghouse_test_proto_goTypes,
		DependencyIndexes: file_api_loghouse_test_loghouse_test_proto_depIdxs,
		EnumInfos:         file_api_loghouse_test_loghouse_test_proto_enumTypes,
		MessageInfos:      file_api_loghouse_test_loghouse_test_proto_msgTypes,
	}.Build()
	File_api_loghouse_test_loghouse_test_proto = out.File
	file_api_loghouse_test_loghouse_test_proto_rawDesc = nil
	file_api_loghouse_test_loghouse_test_proto_goTypes = nil
	file_api_loghouse_test_loghouse_test_proto_depIdxs = nil
}
